version: '3.9'
services:
  flask-app:
    build:
      context: ./flask_app
    container_name: flask-app
    restart: always
    environment:
      USER_NAME: root
      USER_PWD: root_password
      DB_URL: mongo
    expose:
      - 8080
    depends_on:
      - mongo
    networks:
      - flask-mongo
      - flask-nginx


  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80" 
    depends_on:
      - flask-app
    networks:
      - flask-nginx


  mongo:
    image: mongo:7.0.1
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - flask-mongo


networks:
  flask-mongo:
    driver: bridge
  flask-nginx:
    driver: bridge


volumes:
  mongodbdata:
    driver: local