version: '3.9'
services:
  flask-app:
    build:
      context: ./application
    container_name: flask-app
    restart: always
    environment:
      HOST_NAME: mongodb
      MONGO_DB_USERNAME: jonathan
      MONGO_DB_PASSWORD: shtadler
      SECRET_KEY: shT@bI3rU98RE7878
    expose:
      - 8000
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend


  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80" 
    depends_on:
      - flask-app
    networks:
      - frontend


  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: jonathan
      MONGO_INITDB_ROOT_PASSWORD: shtadler
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge


volumes:
  mongodbdata:
    driver: local