version: '3.9'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "80:5000"  # Map port 5000 in the container to port 80 on the host
    environment:
      MONGO_URI: mongodb://0.0.0.0:27017/ # Replace with your MongoDB URI and database name
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: ProjectDB
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: your_mongodb_password
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongo
    volumes:
      - appdata:/var/www
    networks:
      - flask-mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: ProjectDB
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - flask-mongo


networks:
  flask-mongo:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
