name: Unit testing python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker 
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r tests/requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run mongo container
      uses: docker run -d -p 27017:27017 --name=pytest-mongo mongo:7.0.1

    - name: Test Models with pytest
      run: |
        pytest app_tests/test_models.py

    - name: Test Routes with pytest
      run: |
        pytest app_tests/test_routes.py