name: Build and push image to dockerhub

on:
  workflow_run:
    workflows: ["Merge feature to main"]
    types:
      - completed

jobs:
  build-image:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
       ref: feature
      #  path: flask-app/
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker 
      uses: docker/setup-buildx-action@v2
    
    - name: Get Commit Message
      id: get_commit_message
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_TOKEN }} 

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
       push: true
       context: ./application
       file: ./application/Dockerfile
       tags: ${{ secrets.DOCKER_USER }}/compound-interest:${{ steps.get_commit_message.outputs.message }}
