name: Containerized Enviorment Test

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
    - completed
      
jobs:
    Containerized-testing:

        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r containerized-env/requirements.txt
            
        - uses: isbang/compose-action@v1.5.1
          with:
            compose-file: "./containerized-env/docker-compose.yaml"

        - name: Post data to nginx
          run: |
            containerized-env/post_data_to_nginx.sh
    
        - name: Test data posted to mongodb
          run: |
            pytest containerized-env/test_data_posted_to_mongodb.py