name: Merge feature to main and build image

on:
  workflow_run:
    workflows: ["Containerized Enviorment Test"]
    types:
      - completed


jobs:
  merge-main:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@master

    - name: Merge to main
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: feature
        target_branch: master
        github_token: ${{ secrets.GIT_TOKEN }}

  build-image:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
       ref: feature
      #  path: flask-app/
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker 
      uses: docker/setup-buildx-action@v2
    
    - name: Get Commit Message
      id: get_commit_message
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_TOKEN }} 

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
       push: true
       context: ./application
       file: ./application/Dockerfile
       tags: ${{ secrets.DOCKER_USER }}/compound-interest:${{ steps.get_commit_message.outputs.message }}